### PR TITLE
Tidying the routes

### LINKED ISSUE #37: Sort out routes
Sort out routes

### PR DESCRIPTION
**Pull request by domvernon**
closes #37 

Co-authored-by: reenz <17711442+reenz@users.noreply.github.com>
Co-authored-by: Tagrand <24781073+Tagrand@users.noreply.github.com>

### CODE REVIEW

**Review by ealitten — COMMENTED** [review]
So what's the URL for the main page now? Is this now the homepage>?

**Review by reenz — APPROVED** [review]
:shipit:

**Review by Gleoman — APPROVED** [review]
:shipit:

**Review by OutWooods — APPROVED** [review]
🚢 🇮🇹

**Review by ealitten — APPROVED** [review]

**Pull request merged**
