### PR TITLE
Training docs

### LINKED ISSUE #13: Documentation of steps for Machine Learning
- [x] Intro
- [x] Data munging
- [ ] Training the model (Ed L & Tom)
- [x] Exporting & upload
- [x] Django (Ed G, Dom, Reena)
- [x] Heroku & ML engine

### PR DESCRIPTION
**Pull request by OutWooods**
Add first draft for training

Closes #13

### CODE REVIEW

**Review by ealitten — APPROVED** [review]
Made some quick edits to training doc and cleaned up README

**Review by domvernon — APPROVED** [review]
🌗

**Review by reenz — APPROVED** [review]
:shipit:

**Comment by ealitten** [comment]
Is this ready to go now?

**Review by Gleoman — APPROVED** [review]
:shipit:

**Pull request merged**
