### PR TITLE
tidied up django urls, views and templates / also added in some basic html

### PR DESCRIPTION
**Pull request by Gleoman**
… html drop down selectors to later expand upon and link up with the database + an extra test

### CODE REVIEW

**Review by ealitten — COMMENTED** [review]
Looks good but I don't think the __pycache__/* files should be on here; there's already a pattern in .gitignore but it doesn't seem to be doing the trick. Also maybe geckodriver log

**Review by OutWooods — APPROVED** [review]
:shipit:

**Review by reenz — APPROVED** [review]
:shipit:

**Review by domvernon — APPROVED** [review]
:shipit: For now, but the gitignore has a bit of duplication we could cleanup a bit later.

**Review by ealitten — APPROVED** [review]

**Pull request merged**
