### PR TITLE
script to use random forest classifier and model all battle combinations

### PR DESCRIPTION
**Pull request by domvernon**
cd into pokemon and run the script, it should build the csv for you

### CODE REVIEW

**Review by OutWooods — APPROVED** [review]
:shipit:

**Review by reenz — APPROVED** [review]
:shipit:

**Review by OutWooods — CHANGES_REQUESTED** [review]
Looks good, could you go through this with us tomorrow? (Also I've made the CSV, thanks!)

**Review by Gleoman — APPROVED** [review]
Would be great to chat through tomorrow Dom just to understand a bit more about how some of the Python is working

**Comment by Gleoman** [comment]
:shipit:

**Review by OutWooods — APPROVED** [review]

**Review by ealitten — APPROVED** [review]

**Pull request merged**
