### PR TITLE
Add project link + explanation to readme

### PR DESCRIPTION
**Pull request by ealitten**
Added the hosted link to the readme, and an explanation for why it's super slow first time around (hosted link is already at the top so probably good to explain it's google's fault not ours)

### CODE REVIEW

**Review by OutWooods — APPROVED** [review]
:shipit:

**Review by reenz — APPROVED** [review]
:shipit:

**Review by domvernon — APPROVED** [review]
🚀

**Comment by ealitten** [comment]
@Gleoman ?

**Comment by Gleoman** [comment]
:shipit:

Apologies on late response. Hectic week and some plonker hit me with his car while I was on the way to an interview this morning...

**Pull request merged**
